spring.application.name=Weather-App
weather.api.key=d3cafe6dc7be4a2baa793210250509
weather.api.url=https://api.weatherapi.com/v1/current.json
weather.forecast.url= http://api.weatherapi.com/v1/forecast.json
